# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(choices=[('amazon', 'Amazon'), ('best-buy', 'Best Buy'), ('ebay', 'Ebay'), ('newegg', 'Newegg'), ('walmart', 'Walmart')], max_length=10)),
                ('condition', models.CharField(choices=[('all', 'All'), ('new', 'New'), ('used', 'Used'), ('refurb', 'Refurbished')], default='all', max_length=10)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variant')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('condition', models.CharField(max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping_type', models.CharField(blank=True, max_length=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('seller', models.CharField(blank=True, max_length=255)),
                ('rating', models.CharField(blank=True, max_length=25)),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Listing')),
            ],
        ),
    ]
