# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurb', 'Refurbished')], max_length=10, null=True),
        ),
    ]
