# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20180413_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='time',
            new_name='update_time',
        ),
        migrations.AddField(
            model_name='listing',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
