# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20180413_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('refurb', 'Refurbished')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='retailer',
            field=models.CharField(choices=[('amazon', 'Amazon')], max_length=10),
        ),
    ]
