# Generated by Django 2.2.6 on 2019-10-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_auto_20180427_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='url',
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
