# Generated by Django 2.2.6 on 2019-10-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20191014_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='price',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurb', 'Refurbished')], max_length=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('prime', 'Prime')], max_length=10),
        ),
    ]
