# Generated by Django 2.2.6 on 2019-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_auto_20191014_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='rating',
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD')], max_length=3),
        ),
    ]
