# Generated by Django 2.2.6 on 2019-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20191014_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3),
        ),
    ]
