# Generated by Django 2.2.6 on 2019-10-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191014_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='model',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='upc',
        ),
    ]
