# Generated by Django 2.2.6 on 2019-10-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191014_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='msrp',
        ),
    ]
