# Generated by Django 2.2.6 on 2019-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_variant_msrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='ean',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='variant',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='upc',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
