# Generated by Django 2.2.6 on 2019-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191014_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='ean',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='variant',
            name='upc',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
